### ISSUE TITLE
[1.11.2] Lava Crystal Spawning Issue

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#96]
**ArmorPlus Version**:
armorplus-1.11.2-9.5.3.4-beta

**TheDragonLib Version**:
thedragonlib-1.11.2-2.2.3

**MinecraftForge Version**:
forge-1.11.2-13.20.0.2226-universal

**Minecraft Version**:
minecraft_server.1.11.2

**Client or Server?**:
- [x] Client
- [x] Server
Both!

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
Not crash issue

**What happens / happened?**:
Lava Crystal Blocks are not spawned.

I set armorplus.cfg. see follow plz.         
----
I:lavaCrystalOverworldRarity=1
I:lavaCrystalOverworldRarityFixed=1
----
and I created a new world on my server, then mining while 1hour. but no blocks I could find.
tried another one too.
----
B:enableLavaCrystalOreTheNetherGen=true
I:lavaCrystalTheNetherMaxYSpawn=255
I:lavaCrystalTheNetherMinYSpawn=0
I:lavaCrystalTheNetherRarity=1
----
same result in Nether.
( but, Nether case maybe sponge problem. )

I did same actions at Single Play. but I could not find blocks.

**How can I reproduce it?**:

**(Optional) Mod List**:
[MC 1.11.X] BetterCombatMod 1.4
AbyssalCraft-1.11.2-1.9.3.10
armorplus-1.11.2-9.5.3.4-beta
BetterSprinting  MC-1.11.2  v1.1.9
BiomesOPlenty-1.11.2-6.0.1.2145-universal
chiselsandbits-13.9
CommandSigns-API-6.0.0-1.3.1
CosmeticArmorReworked-1.11.2-v1a
deathpenalty-v1.1
flatcoloredblocks-mc1.11-5.1
griefprevention-1.11.2-3.1.0.239
journeymap-1.11.2-5.4.4
LuckPerms-Sponge-2.17.11
MoreDyes-1.11-1.1.1
Nucleus-0.20.0-S5.1-1.10.2-plugin
NucleusMixins-0.15.0-S5-mixinplugin
projectportals-5.1.0-0.13.6
projectworlds-5.1.0-0.11.4
RealisticTorches-1.11.2-2.1.0
spongeforge-1.11.2-2226-6.0.0-BETA-2112
thedragonlib-1.11.2-2.2.3
TotalEconomy-v1.5.3

**Comment by sokratis12GR** [comment]
hmm interesting, could you try making the "Fixed" one rareity to 3-4
and the Y levels min 6 - max 16 ?

**Comment by ghost** [comment]
I will try "Fixed" to 3 or 4 and dig Y 6 - 16. ;D

**Comment by ghost** [comment]
I set "Fixed=3" then dig to the north. I got 11gems(Biomes O' Plenty), 1stack Iron Ores, 24 Gold Ores, many Redstone ores and coal ores. I kept y >= 9 and y <= 12. but I could not find Lava Crystal. ;(

**Comment by sokratis12GR** [comment]
alright, considering this a bug

**Comment by ghost** [comment]
Thank you, sir!

**Comment by sokratis12GR** [comment]
Lol, this issue is critical tho. Without any lava crystals you cannot progress at all in a+ 1.11.2

**Comment by sokratis12GR** [comment]
Try to make "Fixed" = 10-20

**Comment by sokratis12GR** [comment]
and vein size from 2- 4

**Comment by ghost** [comment]
I tried to mining with Fixed=20 and VeinSize=4 about 30min in the new overworld. but I can't find lava crystal. then, use "/gamemode 3" and search around. no lava crystal. ;( it is the better thing if I can find lava crystal in Nether, but still no lava crystal in Nether too.

**Comment by sokratis12GR** [comment]
Latest update should fix the issues, re-create a new world and try again. Please let me know if that time it worked

**Comment by ghost** [comment]
Report:

1. delete armorplus.cfg
2. launch Minecraft client
3. create a new world for single play with default settings except for cheat.
4. /gamemode 3
5. looking around, then I can find Lava Crystals !!

Lava Crystals spawn correctly with Biomes O Plenty.

But I still can't find Lava Crystals on my server ( SPONGE FORGE ).

1. delete armorplus.cfg on my server.
2. launch Client and Server.
3. login to Server.
4. create a new world with default settings.
5. /gamemode 3
6. looking around, but no Lava Crystals.

So, this problem is relative SPONGE issue I think. Some other Mods work correctly with sponge-forge, but it is your decision. I want to say GJ and Thank you so much!

**Comment by sokratis12GR** [comment]
Alright. thanks for the report and the help on solving the issue :). May I consider closing this issue ?

**Comment by ghost** [comment]
Sure! Thank you!!
